columns_rename = {'1':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge',
                        'Appliance2':'Freezer(1)',
                        'Appliance3':'Freezer(2)',
                        'Appliance4':'Washer Dryer',
                        'Appliance5':'Washing Machine',
                        'Appliance6':'Dishwasher',
                        'Appliance7':'Computer',
                        'Appliance8':'Television Site',
                        'Appliance9':'Electric Heater' },
                '2':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge-Freezer',
                        'Appliance2':'Washing Machine',
                        'Appliance3':'Dishwasher',
                        'Appliance4':'Television Site',
                        'Appliance5':'Microwave',
                        'Appliance6':'Toaster',
                        'Appliance7':'Hi-Fi',
                        'Appliance8':'Kettle',
                        'Appliance9':'Overhead Fan' },
                '3':{'Time': 'Timestamp', 
                        'Appliance1': 'Toaster',
                        'Appliance2':'Fridge-Freezer',
                        'Appliance3':'Freezer',
                        'Appliance4':'Tumble Dryer',
                        'Appliance5':'Dishwasher',
                        'Appliance6':'Washing Machine',
                        'Appliance7':'Television Site',
                        'Appliance8':'Microwave',
                        'Appliance9':'Kettle' }, 
                '4':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge',
                        'Appliance2':'Freezer',
                        'Appliance3':'Fridge-Freezer',
                        'Appliance4':'Washing Machine(1)',
                        'Appliance5':'Washing Machine(2)',
                        'Appliance6':'Desktop Computer',
                        'Appliance7':'Television Site',
                        'Appliance8':'Microwave',
                        'Appliance9':'Kettle' },
                '5':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge-Freezer',
                        'Appliance2':'Tumble Dryer',
                        'Appliance3':'Washing Machine',
                        'Appliance4':'Dishwasher',
                        'Appliance5':'Desktop Computer',
                        'Appliance6':'Television Site',
                        'Appliance7':'Microwave',
                        'Appliance8':'Kettle',
                        'Appliance9':'Toaster' },
                '6':{'Time': 'Timestamp', 
                        'Appliance1': 'Freezer',
                        'Appliance2':'Washing Machine',
                        'Appliance3':'Dishwasher',
                        'Appliance4':'MJY Computer',
                        'Appliance5':'TV/Satellite',
                        'Appliance6':'Microwave',
                        'Appliance7':'Kettle',
                        'Appliance8':'Toaster',
                        'Appliance9':'PGM Computer' },
                  
                '7':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge',
                        'Appliance2':'Freezer(1)',
                        'Appliance3':'Freezer(2)',
                        'Appliance4':'Tumble Dryer',
                        'Appliance5':'Washing Machine',
                        'Appliance6':'Dishwasher',
                        'Appliance7':'Television Site',
                        'Appliance8':'Toaster',
                        'Appliance9':'Kettle' },
                  
                 '8':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge',
                        'Appliance2':'Freezer',
                        'Appliance3':'Washer Dryer',
                        'Appliance4':'Washing Machine',
                        'Appliance5':'Toaster',
                        'Appliance6':'Computer',
                        'Appliance7':'Television Site',
                        'Appliance8':'Microwave',
                        'Appliance9':'Kettle' },
                  
                  '9':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge-Freezer',
                        'Appliance2':'Washer Dryer',
                        'Appliance3':'Washing Machine',
                        'Appliance4':'Dishwasher',
                        'Appliance5':'Television Site',
                        'Appliance6':'Microwave',
                        'Appliance7':'Kettle',
                        'Appliance8':'Hi-Fi',
                        'Appliance9':'Electric Heater' },
                  
                  '10':{'Time': 'Timestamp', 
                        'Appliance1': 'Magimix(Blender)',
                        'Appliance2':'Toaster',
                        'Appliance3':'Chest Freezer',
                        'Appliance4':'Fridge-Freezer',
                        'Appliance5':'Washing Machine',
                        'Appliance6':'Dishwasher',
                        'Appliance7':'Television Site',
                        'Appliance8':'Microwave',
                        'Appliance9':'K Mix' },
                  
                  '11':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge',
                        'Appliance2':'Fridge-Freezer',
                        'Appliance3':'Washing Machine',
                        'Appliance4':'Dishwasher',
                        'Appliance5':'Computer Site',
                        'Appliance6':'Microwave',
                        'Appliance7':'Kettle',
                        'Appliance8':'Router',
                        'Appliance9':'Hi-Fi' },
                  
                  '12':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge-Freezer',
                        'Appliance2':'Unknown1',
                        'Appliance3':'Unknown2',
                        'Appliance4':'Computer Site',
                        'Appliance5':'Microwave',
                        'Appliance6':'Kettle',
                        'Appliance7':'Toaster',
                        'Appliance8':'Television',
                        'Appliance9':'Unknown3' },
                  
                  '13':{'Time': 'Timestamp', 
                        'Appliance1': 'Television Site',
                        'Appliance2':'Freezer',
                        'Appliance3':'Washing Machine',
                        'Appliance4':'Dishwasher',
                        'Appliance5':'Unknown',
                        'Appliance6':'Network Site',
                        'Appliance7':'Microwave',
                        'Appliance8':'Microwave(2)',
                        'Appliance9':'Kettle' },
                  
                  
                  '15':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge-Freezer',
                        'Appliance2':'Tumble Dryer',
                        'Appliance3':'Washing Machine',
                        'Appliance4':'Dishwasher',
                        'Appliance5':'Computer Site',
                        'Appliance6':'Television Site',
                        'Appliance7':'Microwave',
                        'Appliance8':'Hi-Fi',
                        'Appliance9':'Toaster' },
                  
                  '16':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge-Freezer(1)',
                        'Appliance2':'Fridge-Freezer(2)',
                        'Appliance3':'Electric Heater(1)',
                        'Appliance4':'Electric Heater(2)',
                        'Appliance5':'Washing Machine',
                        'Appliance6':'Dishwasher',
                        'Appliance7':'Computer Site',
                        'Appliance8':'Television Site',
                        'Appliance9':'Dehumidifier' },
                  
                  '17':{'Time': 'Timestamp', 
                        'Appliance1': 'Freezer',
                        'Appliance2':'Fridge-Freezer',
                        'Appliance3':'Tumble Dryer',
                        'Appliance4':'Washing Machine',
                        'Appliance5':'Computer Site',
                        'Appliance6':'Television Site',
                        'Appliance7':'Microwave',
                        'Appliance8':'Kettle',
                        'Appliance9':'TV Site(Bedroom)' },
                  
                  '18':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge(garage)',
                        'Appliance2':'Freezer(garage)',
                        'Appliance3':'Fridge-Freezer',
                        'Appliance4':'Washer Dryer(garage)',
                        'Appliance5':'Washing Machine',
                        'Appliance6':'Dishwasher',
                        'Appliance7':'Desktop Computer',
                        'Appliance8':'Television Site',
                        'Appliance9':'Microwave' },
                  
                  '19':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge Freezer',
                        'Appliance2':'Washing Machine',
                        'Appliance3':'Television Site',
                        'Appliance4':'Microwave',
                        'Appliance5':'Kettle',
                        'Appliance6':'Toaster',
                        'Appliance7':'Bread-maker',
                        'Appliance8':'Games Console',
                        'Appliance9':'Hi-Fi' },
                  
                  '20':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge',
                        'Appliance2':'Freezer',
                        'Appliance3':'Tumble Dryer',
                        'Appliance4':'Washing Machine',
                        'Appliance5':'Dishwasher',
                        'Appliance6':'Computer Site',
                        'Appliance7':'Television Site',
                        'Appliance8':'Microwave',
                        'Appliance9':'Kettle' },
                  
                  '21':{'Time': 'Timestamp', 
                        'Appliance1': 'Fridge-Freezer',
                        'Appliance2':'Tumble Dryer',
                        'Appliance3':'Washing Machine',
                        'Appliance4':'Dishwasher',
                        'Appliance5':'Food Mixer',
                        'Appliance6':'Television',
                        'Appliance7':'Kettle',
                        'Appliance8':'Vivarium',
                        'Appliance9':'Pond Pump' },}


label = {'1':['Timestamp', 
                     'Fridge',
                     'Freezer(1)',
                     'Freezer(2)',
                     'Washer Dryer',
                     'Washing Machine',
                    'Dishwasher',
                     'Computer',
                    'Television Site',
                    'Electric Heater' ],
         
          '2':['Timestamp', 
                    'Fridge-Freezer',
                    'Washing Machine',
                    'Dishwasher',
                    'Television Site',
                     'Microwave',
                    'Toaster',
                    'Hi-Fi',
                    'Kettle',
                    'Overhead Fan'],
         
         
                '3':['Timestamp', 
                        'Toaster',
                        'Fridge-Freezer',
                        'Freezer',
                        'Tumble Dryer',
                        'Dishwasher',
                        'Washing Machine',
                        'Television Site',
                        'Microwave',
                        'Kettle' ], 
						
						
                '4':['Timestamp', 
                        'Fridge',
                        'Freezer',
                        'Fridge-Freezer',
                        'Washing Machine(1)',
                        'Washing Machine(2)',
                        'Desktop Computer',
                        'Television Site',
                        'Microwave',
                        'Kettle' ],

						
                '5':['Timestamp', 
                        'Fridge-Freezer',
                        'Tumble Dryer',
                        'Washing Machine',
                        'Dishwasher',
                        'Desktop Computer',
                        'Television Site',
                        'Microwave',
                        'Kettle',
                        'Toaster' ],

                '6':['Timestamp', 
                        'Freezer',
                        'Washing Machine',
                        'Dishwasher',
                        'MJY Computer',
                        'TV/Satellite',
                        'Microwave',
                        'Kettle',
                        'Toaster',
                        'PGM Computer' ],
                  
				  
                '7':['Timestamp', 
                        'Fridge',
                        'Freezer(1)',
                        'Freezer(2)',
                        'Tumble Dryer',
                        'Washing Machine',
                        'Dishwasher',
                        'Television Site',
                        'Toaster',
                        'Kettle' ],
						
                  
                 '8':['Timestamp', 
                        'Fridge',
                        'Freezer',
                        'Washer Dryer',
                        'Washing Machine',
                        'Toaster',
                        'Computer',
                        'Television Site',
                        'Microwave',
                        'Kettle' ],
						
                  
                  '9':['Timestamp', 
                        'Fridge-Freezer',
                        'Washer Dryer',
                        'Washing Machine',
                        'Dishwasher',
                        'Television Site',
                        'Microwave',
                        'Kettle',
                        'Hi-Fi',
                        'Electric Heater' ],
                  
				  
                  '10':['Timestamp', 
                        'Magimix(Blender)',
                        'Toaster',
                        'Chest Freezer',
                        'Fridge-Freezer',
                        'Washing Machine',
                        'Dishwasher',
                        'Television Site',
                        'Microwave',
                        'K Mix' ],
                  
				  
                  '11':['Timestamp', 
                        'Fridge',
                        'Fridge-Freezer',
                        'Washing Machine',
                        'Dishwasher',
                        'Computer Site',
                        'Microwave',
                        'Kettle',
                        'Router',
                        'Hi-Fi' ],
                  
				  
                  '12':['Timestamp', 
                        'Fridge-Freezer',
                        'Unknown1',
                        'Unknown2',
                        'Computer Site',
                        'Microwave',
                        'Kettle',
                        'Toaster',
                        'Television',
                        'Unknown3' ],
                  
				  
                  '13':['Timestamp', 
                        'Television Site',
                        'Freezer',
                        'Washing Machine',
                        'Dishwasher',
                        'Unknown',
                        'Network Site',
                        'Microwave',
                        'Microwave(2)',
                        'Kettle' ],
                  
                  
                  '15':['Timestamp', 
                        'Fridge-Freezer',
                        'Tumble Dryer',
                        'Washing Machine',
                        'Dishwasher',
                        'Computer Site',
                        'Television Site',
                        'Microwave',
                        'Hi-Fi',
                        'Toaster' ],
                  
				  
                  '16':['Timestamp', 
                        'Fridge-Freezer(1)',
                        'Fridge-Freezer(2)',
                        'Electric Heater(1)',
                        'Electric Heater(2)',
                        'Washing Machine',
                        'Dishwasher',
                        'Computer Site',
                        'Television Site',
                        'Dehumidifier' ],
                  
				  
                  '17':['Timestamp', 
                        'Freezer',
                        'Fridge-Freezer',
                        'Tumble Dryer',
                        'Washing Machine',
                        'Computer Site',
                        'Television Site',
                        'Microwave',
                        'Kettle',
                        'TV Site(Bedroom)' ],
                  
                  '18':['Timestamp', 
                        'Fridge(garage)',
                        'Freezer(garage)',
                        'Fridge-Freezer',
                        'Washer Dryer(garage)',
                        'Washing Machine',
                        'Dishwasher',
                        'Desktop Computer',
                        'Television Site',
                        'Microwave' ],
                  
				  
                  '19':['Timestamp', 
                        'Fridge Freezer',
                        'Washing Machine',
                        'Television Site',
                        'Microwave',
                        'Kettle',
                        'Toaster',
                        'Bread-maker',
                        'Games Console',
                        'Hi-Fi' ],
						
                  
                  '20':['Timestamp', 
                        'Fridge',
                        'Freezer',
                        'Tumble Dryer',
                        'Washing Machine',
                        'Dishwasher',
                        'Computer Site',
                        'Television Site',
                        'Microwave',
                        'Kettle' ],
                  
				  
                  '21':['Timestamp', 
                        'Fridge-Freezer',
                        'Tumble Dryer',
                        'Washing Machine',
                        'Dishwasher',
                        'Food Mixer',
                        'Television',
                        'Kettle',
                        'Vivarium',
                        'Pond Pump' ],

}